### ISSUE TITLE
希望添加一个浅色模式或者增强文字和背景的对比度

### ISSUE THREAD

**Issue by Zpcola** [imfile-io/imfile-desktop#10]
哦，我的伙计
这个深色的背景色和灰色的字体让我看不清
希望添加一个浅色模式
<img width="807" alt="Snipaste_2024-04-17_11-19-34" src="https://github.com/imfile-io/imfile-desktop/assets/116626041/3181c07d-f4ff-459f-9d4f-120df9583342">

**Comment by FaintGhost** [comment]
支持，散光看着特别难受

**Comment by chenjia404** [comment]
浅色模式加入计划中。

**Comment by huanghaobaobao** [comment]
试用了一下，没找到浅色模式开关，来提issue，发现不止我难受啊😂

**Comment by zhd-love** [comment]
的确，当前的外观的确看着累。

**Comment by plumlis** [comment]
而且喜欢增加 trayicon 的深色和浅色的选择，gnome-shell 下图标是黑色的，看不到。

**Comment by StarryskyLL** [comment]
发现没有浅色，刚想提issue，就来搜一下，发现有人提了，我也是看深色有点难受，上面有大佬说散光看深色特别难受，我可能也是因为散光（散光大概两百，之前并不知道散光看深色会难受）所以才比较喜欢浅色

**Comment by Ramon403** [comment]
发现没有浅色，刚想提issue，就来搜一下，发现有人提了,
这个配色白天看了眼瞎
> [!IMPORTANT]
> 强烈建议增加一个浅色主题

**Comment by chenjia404** [comment]
1.0.8版本增加了浅色模式。
