### ISSUE TITLE
[BUG]: Mac Arm 提示已损坏，无法打开

### ISSUE THREAD

**Issue by oneCatZz** [imfile-io/imfile-desktop#107]
### Bug 描述

![CleanShot 2024-05-07 at 10 57 36@2x](https://github.com/imfile-io/imfile-desktop/assets/32626686/395b8669-eb9b-47bb-9b3f-1a98d45509eb)
下载后打开时提示已损坏，无法打开

### Motrix 版本

imFile-1.0.8-arm64.dmg

### 环境

  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 100.88 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 17.4.1

### 复现步骤

下载 imFile-1.0.8-arm64.dmg 后打开报错

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by DickDock** [comment]
终端输入以下命令置信即可

sudo xattr -r -d com.apple.quarantine /Applications/imFile.app
