### ISSUE TITLE
有linux版本嘛

### ISSUE THREAD

**Issue by LIHAQ** [imfile-io/imfile-desktop#11]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by xihale** [comment]
[#25](https://github.com/imfile-io/imfile-desktop/issues/25#issuecomment-2067621423)
A arch linux aur package, you can look at the PKGBUILD then make your similar own for your OS.(If you are not using arch linux)
https://aur.archlinux.org/packages/imfile-electron

**Comment by chenjia404** [comment]
https://github.com/imfile-io/imfile-desktop/releases
