### ISSUE TITLE
[BUG]: 下载完成后会剩余aria2文件

### ISSUE THREAD

**Issue by LIHAQI** [imfile-io/imfile-desktop#12]
### Bug 描述

下载完成后会剩余aria2文件
![image](https://github.com/imfile-io/imfile-desktop/assets/57976650/ed91c665-e13d-4f48-b30c-79576de79cb3)

### Motrix 版本

引擎版本 1.37.0
electron 30.0.0
chrome 124.0.6367.49

### 环境

无

### 复现步骤

无

### 额外信息

无

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by chenjia404** [comment]
这个文件体积很小，保留这个文件便于重新开始任务。

**Comment by LIHAQI** [comment]
> 这个文件体积很小，保留这个文件便于重新开始任务。

但是这样下载完成，如果不需要重新开始，目录里就会多个文件。如果下载了多个任务，到时候下载目录就会很乱

**Comment by kuailaishishei** [comment]
找个网页UI的aria2设置-高级设置-强制保存改为否即可

**Comment by LIHAQI** [comment]
> 找个网页UI的aria2设置-高级设置-强制保存改为否即可

好了，多谢

**Comment by chenjia404** [comment]
> > 这个文件体积很小，保留这个文件便于重新开始任务。
> 
> 但是这样下载完成，如果不需要重新开始，目录里就会多个文件。如果下载了多个任务，到时候下载目录就会很乱

下一个版本去掉这个。
