### ISSUE TITLE
Tag `v1.0.9` refers to a broken and deleted commit

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [imfile-io/imfile-desktop#121]
The tag `v1.0.9` refers to commit `840f2e4f8f2fb5bb1d57b7e6e78c74f1cf55db29`, but this commit is broken and already been deleted. This can make distro maintainers to packaging difficult and causes misunderstanding.

**Comment by chenjia404** [comment]
ok，it update

**Comment by chenjia404** [comment]
I create a new version

**Comment by chenjia404** [comment]
Migrate to yarn and create v1.1.0？
