### ISSUE TITLE
[BUG]: 从服务器同步track列表仍然为空。

### ISSUE THREAD

**Issue by HumanMus1c** [imfile-io/imfile-desktop#122]
### Bug 描述

点击“从服务器同步”按钮之后，下方的track列表仍然是空的。
![recording](https://github.com/imfile-io/imfile-desktop/assets/46023154/6d4eb640-0493-4236-99a9-e3d0679c20dc)

### Motrix 版本

 Version 1.0.9
引擎版本 1.37.0
electron 30.0.1
chrome 124.0.6367.60
![image](https://github.com/imfile-io/imfile-desktop/assets/46023154/12abdc1e-06a5-4928-8840-58f3fd7874af)

### 环境

 System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 6.95 GB / 15.91 GB
  Binaries:
    Node: 18.16.0 - D:\Program Files\nodejs\node.EXE
    npm: 9.6.6 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527

### 复现步骤

![recording](https://github.com/imfile-io/imfile-desktop/assets/46023154/0e74130f-1eed-43dd-bd68-819d6f3a7cef)

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by chenjia404** [comment]
你的网络是否可以成功访问这几个链接呢？

**Comment by hub010** [comment]
我给你看看我的，希望对你有所帮助。第一你要确定track链接是否有效，是否需要梯子。第二在系统C:\Users\Administrator\AppData\Roaming\imFile里，是否有dht.dat文件（必须），否则磁力无效或没有速度。
![1](https://github.com/imfile-io/imfile-desktop/assets/164721841/80334ba1-658b-48e7-b8b9-121dbc240051)
![2](https://github.com/imfile-io/imfile-desktop/assets/164721841/90bb5e88-204c-46f9-9e65-16374d014435)

**Comment by HumanMus1c** [comment]
> 你的网络是否可以成功访问这几个链接呢？

可以正常访问github repo，但是因为下载的是最新版本1.0.9的便携版独立exe程序，就有这个问题。换成最新安装版本就没有问题了。
