### ISSUE TITLE
archlinux安装包，颜色定制，多下载格式支持

### ISSUE THREAD

**Issue by petercao** [imfile-io/imfile-desktop#25]
1.可以提供下archlinux上的安装包，之前motrix都是有的；
2.界面颜色等希望能给成可定制的，目前全黑；
3.希望百度盘，阿里盘，youtube等，磁力，bt种子，等等链接下载都能提供或者以插件提供

**Comment by xihale** [comment]
I had created the aur package: https://aur.archlinux.org/packages/imfile-electron

**Comment by chenjia404** [comment]
https://github.com/imfile-io/imfile-desktop/releases

**Comment by xihale** [comment]
> https://github.com/imfile-io/imfile-desktop/releases

如果可以直接提供 `app.asar` 文件, 那么 aur PKGBUILD 制作工作流将会简单不少, 同理, 其他系统的类似构造脚本也将变得简单很多.

**Comment by chenjia404** [comment]
我可以每次提供一个 app.asar ，这个应该和平台无关，我等会测试一下。

**Comment by xihale** [comment]
> 我可以每次提供一个 app.asar ，这个应该和平台无关，我等会测试一下。

没有看到 Release 里面的 `.asar` 文件，是遇到什么问题了吗?
