### ISSUE TITLE
每天自动更新 Tracker 服务器列表 这个功能现在在哪里？

### ISSUE THREAD

**Issue by breathiness** [imfile-io/imfile-desktop#36]
之前 motrix 在设置里是可以添加 Tracker 服务器列表链接，然后拉取链接内地址的。（虽然有BUG无法正常使用）

**Comment by breathiness** [comment]
好吧，找到了。之前眼瞎没发现进阶设置

**Comment by efaun** [comment]
> 好吧，找到了。之前瞎眼没发现进阶设置（虽然之前的BUG还是在，没办法正常更新）

我也瞎眼, 请问进阶设置在哪🤣
![image](https://github.com/imfile-io/imfile-desktop/assets/13315821/23267543-4b9d-4281-953c-3938f49c1d63)
