### ISSUE TITLE
[BUG]:国内下载无速度

### ISSUE THREAD

**Issue by jinyuanqing** [imfile-io/imfile-desktop#4]
### Bug 描述

国内下载无速度

### Motrix 版本

最新版

### 环境

Windows

### 复现步骤

国内下载无速度

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by chenjia404** [comment]
你是什么网络，下载的资源热度怎么样？

**Comment by jinyuanqing** [comment]
您好,我是移动光纤,下载的资源热度挺高的.用迅雷速度飞起的.我这边用其他磁力或者bt工具,都这样.

**Comment by wao1201** [comment]
有没有想过是迅雷的独特机制导致下载速度快，其他走通用 torrent 机制的没办法办到，特别是在移动的宽带下

**Comment by Pizzdd** [comment]
移动网络的话基本可以放弃用Bt一类软件，移动网络机制如此。
迅雷和移动机房有合作所以有下载速度。

**Comment by jinyuanqing** [comment]
ok
