### ISSUE TITLE
[BUG]: METADATA下载时间过长

### ISSUE THREAD

**Issue by wgetnz** [imfile-io/imfile-desktop#59]
### Bug 描述

磁力链接：magnet:?xt=urn:btih:4a95293ea64810dec5af1702e0bd98904b964692&dn=zh-cn_windows_11_consumer_editions_version_23h2_updated_april_2024_x64_dvd_d986680b.iso&xl=7008280576

发现添加任务后，会先进行METADATA下载，这个时间大概需要花费3-5分钟，我觉得这个是可以优化的，将磁力转换成种子后，会进行直接下载，没有METADATA下载过程，可以节省时间，转换的网站如https://magnet2torrent.com/，希望能改进这一点，感谢开发人员幸苦付出

### Motrix 版本

Version 1.0.7
引擎版本 1.37.0
electron 30.0.1
chrome 124.0.6367.6

### 环境

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 47.41 GB / 63.74 GB
  Binaries:
    Node: 21.7.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1

### 复现步骤

.

### 额外信息

no

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by TheCGDF** [comment]
不懂BUG的意思就先百度下，这种“我觉得这个是可以优化”的东西不要乱发到BUG issue里。

“METADATA下载”就是在将磁力通过DHT网络转换为类似种子一样的东西，因为你的网络太糟糕了（比如中国移动/长城/铁通/校园网，或者新疆/河南/福建等封锁比较严重的省份）所以导致要3-5分钟才能获取到METADATA。

而你所提到的第三方网站并不是并DHT网络组件（tracker），客户端默认的tracker servers已经内置了几百个（可能更多）这种“网站”，你提到的“3-5分钟”正是在依次尝试连接这些“网站”来获取“种子”。更何况你发的那网站大陆也访问不了，且随时都可能关站，对下载器来说一点用没有。

解决方案：要么你在下载器的设置里开启代理，让下载器通过你的梯子访问trackers（前提是你的梯子没有屏蔽BT）；要么你自己从第三方网站上下载好种子再用下载器打开
