### ISSUE TITLE
[BUG]: 官网出现错别字，“同事”-->“同时”

### ISSUE THREAD

**Issue by soda8890** [imfile-io/imfile-desktop#77]
### Bug 描述

官网出现错别字，“同事”-->“同时”

![image](https://github.com/imfile-io/imfile-desktop/assets/50317417/21228e75-00e5-49dd-882e-48e80507618d)

### Motrix 版本

1.0.7

### 环境

无

### 复现步骤

无

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by chenjia404** [comment]
感谢反馈，已经修复。
