### ISSUE TITLE
请求增加最大线程数

### ISSUE THREAD

**Issue by xukongshizhe** [imfile-io/imfile-desktop#8]
目前版本的每个服务器最大连接数16感觉有点小，能增大到32或64吗？

**Comment by chenjia404** [comment]
一般来讲到了10个连接数，就达到了单个服务器线路带宽的上限了，提高连接数不能等比例的无限提高下载速度。

**Comment by xukongshizhe** [comment]
> 一般来讲到了10个连接数，就达到了单个服务器线路带宽的上限了，提高连接数不能等比例的无限提高下载速度。

但有些特殊场景多线程还是有用的。比如在搭配油猴脚本下载夸克网盘（无VIP）的时候，使用Motrix，设置最大线程64后下载速度可以达到2.2MB/秒，使用Imfile。最大线程只有16，速度就只能到500KB/秒。
希望能增加到64，可以根据需要自己进行设定合适的线程数。

**Comment by chenjia404** [comment]
> > 一般来讲到了10个连接数，就达到了单个服务器线路带宽的上限了，提高连接数不能等比例的无限提高下载速度。
> 
> 但有些特殊场景多线程还是有用的。比如在搭配油猴脚本下载夸克网盘（无VIP）的时候，使用Motrix，设置最大线程64后下载速度可以达到2.2MB/秒，使用Imfile。最大线程只有16，速度就只能到500KB/秒。 希望能增加到64，可以根据需要自己进行设定合适的线程数。

ok，下一个版本提高到64。

**Comment by chenjia404** [comment]
64线程
